# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"?\n\x0c\x44\x65layedReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1e\n\x07request\x18\x02 \x03(\x0b\x32\r.HelloRequest2\xcb\x01\n\tmessenger\x12&\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\x12/\n\x0fServerSaysHello\x12\r.HelloRequest\x1a\x0b.HelloReply0\x01\x12\x31\n\x0fNandinSaysHello\x12\r.HelloRequest\x1a\r.DelayedReply(\x01\x12\x32\n\x10InteractingHello\x12\r.HelloRequest\x1a\x0b.HelloReply(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=13
  _HELLOREQUEST._serialized_end=59
  _HELLOREPLY._serialized_start=61
  _HELLOREPLY._serialized_end=90
  _DELAYEDREPLY._serialized_start=92
  _DELAYEDREPLY._serialized_end=155
  _MESSENGER._serialized_start=158
  _MESSENGER._serialized_end=361
# @@protoc_insertion_point(module_scope)
