# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import msg_pb2 as msg__pb2


class messengerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/messenger/SayHello',
                request_serializer=msg__pb2.HelloRequest.SerializeToString,
                response_deserializer=msg__pb2.HelloReply.FromString,
                )
        self.ServerSaysHello = channel.unary_stream(
                '/messenger/ServerSaysHello',
                request_serializer=msg__pb2.HelloRequest.SerializeToString,
                response_deserializer=msg__pb2.HelloReply.FromString,
                )
        self.NandinSaysHello = channel.stream_unary(
                '/messenger/NandinSaysHello',
                request_serializer=msg__pb2.HelloRequest.SerializeToString,
                response_deserializer=msg__pb2.DelayedReply.FromString,
                )
        self.InteractingHello = channel.stream_stream(
                '/messenger/InteractingHello',
                request_serializer=msg__pb2.HelloRequest.SerializeToString,
                response_deserializer=msg__pb2.HelloReply.FromString,
                )


class messengerServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerSaysHello(self, request, context):
        """Server Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NandinSaysHello(self, request_iterator, context):
        """Client Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InteractingHello(self, request_iterator, context):
        """Both Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_messengerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=msg__pb2.HelloRequest.FromString,
                    response_serializer=msg__pb2.HelloReply.SerializeToString,
            ),
            'ServerSaysHello': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerSaysHello,
                    request_deserializer=msg__pb2.HelloRequest.FromString,
                    response_serializer=msg__pb2.HelloReply.SerializeToString,
            ),
            'NandinSaysHello': grpc.stream_unary_rpc_method_handler(
                    servicer.NandinSaysHello,
                    request_deserializer=msg__pb2.HelloRequest.FromString,
                    response_serializer=msg__pb2.DelayedReply.SerializeToString,
            ),
            'InteractingHello': grpc.stream_stream_rpc_method_handler(
                    servicer.InteractingHello,
                    request_deserializer=msg__pb2.HelloRequest.FromString,
                    response_serializer=msg__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class messenger(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/messenger/SayHello',
            msg__pb2.HelloRequest.SerializeToString,
            msg__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerSaysHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/messenger/ServerSaysHello',
            msg__pb2.HelloRequest.SerializeToString,
            msg__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NandinSaysHello(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/messenger/NandinSaysHello',
            msg__pb2.HelloRequest.SerializeToString,
            msg__pb2.DelayedReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InteractingHello(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/messenger/InteractingHello',
            msg__pb2.HelloRequest.SerializeToString,
            msg__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
